#! /bin/sh

TOOLCHAIN="avr-gcc-toolchain.cmake"

CMAKE_BUILD_ROOT="build"
CMAKE_RELEASE="${CMAKE_BUILD_ROOT}/release"
CMAKE_DEBUG="${CMAKE_BUILD_ROOT}/debug"
CMAKE_MIN_REL="${CMAKE_BUILD_ROOT}/min-release"

cmake -DCMAKE_BUILD_TYPE=Debug -S. -B${CMAKE_DEBUG} -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN} && cmake --build ${CMAKE_DEBUG}
cmake -DCMAKE_BUILD_TYPE=MinSizeRel -S. -B${CMAKE_MIN_REL} -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN} && cmake --build ${CMAKE_MIN_REL}
cmake -DCMAKE_BUILD_TYPE=Release -S. -B${CMAKE_RELEASE} -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN} && cmake --build ${CMAKE_RELEASE}